<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Block\BlockManagerInterface;

/**
* Implements hook_node_view().
*/
function extend_title_node_view(array &$build, NodeInterface $node, $view_mode) {
\Drupal::logger('extend_title')->notice('Node bundle: @type', ['@type' => $node->bundle()]);

if ($node->bundle() === 'article') {

    // Załaduj blok.
    $block_manager = \Drupal::service('plugin.manager.block');
    $config = [];
    $plugin_block = $block_manager->createInstance('title_html_block', $config);
    $render = $plugin_block->build();

    // Dodaj blok po tytule (czyli np. na początku zawartości).
    // array_splice($build['#children'] ?? $build, 1, 0, [['#markup' => '<div data-block="1" class="my-block-wrapper">'] + $render + ['#markup' => '</div>']]);

    $build['title_html_block'] = [
      '#weight' => -9,
    ] + $render;

    /*$build['title_html_block'] = [
      '#markup' => '<div data-block="1" style="color:red">TEST BLOCK</div>',
      '#weight' => -10,
    ];*/
  }
}
